[versions]
agp = "8.2.2"
kotlin = "1.9.22"
composeBom = "2023.10.01"
composeCompiler = "1.5.8"
mpchart = "3.1.0"
accompanist = "0.34.0"
coil = "2.5.0"

[libraries]
androidx-compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "composeBom" }
androidx-compose-compiler = { module = "androidx.compose.compiler:compiler", version.ref = "composeCompiler" }
androidx-material3 = { group = "androidx.compose.material3", name = "material3" }
mpchart = { module = "com.github.PhilJay:MPAndroidChart", version.ref = "mpchart" }
accompanist-permissions = { module = "com.google.accompanist:accompanist-permissions", version.ref = "accompanist" }
accompanist-pager = { module = "com.google.accompanist:accompanist-pager", version.ref = "accompanist" }
accompanist-systemuicontroller = { module = "com.google.accompanist:accompanist-systemuicontroller", version.ref = "accompanist" }
coil-compose = { module = "io.coil-kt:coil-compose", version.ref = "coil" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }